name: "Variants demo using GitHub actions"

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    paths:
      - '*.sch'
      - '*.kicad_pcb'
      - '*.kibot.yaml'
      - 'Makefile'
      - '.github/workflows/kibot_action.yml'
  pull_request:
    paths:
      - '*.sch'
      - '*.kicad_pcb'
      - '*.kibot.yaml'
      - 'Makefile'
      - '.github/workflows/kibot_action.yml'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  ERC:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Run ERC
      uses: INTI-CMNB/KiBot@92fac3958665528621f09a5d8af0b92e8d88cc32
      with:
        kicad: 5
        dir: Generated
        skip: run_drc
        targets: __NONE__

    - name: Retrieve results
      uses: actions/upload-artifact@v2
      with:
        name: ERC_Output
        path: Generated


  DRC:
    runs-on: ubuntu-latest
    needs: ERC

    steps:
    - uses: actions/checkout@v2

    - name: Run DRC
      uses: INTI-CMNB/KiBot@92fac3958665528621f09a5d8af0b92e8d88cc32
      with:
        kicad: 5
        dir: Generated
        skip: run_erc
        targets: __NONE__

    - name: Retrieve results
      uses: actions/upload-artifact@v1
      with:
        name: DRC_Output
        path: Generated


  default:
    name: "Default variant"
    runs-on: ubuntu-latest
    needs: [ERC, DRC]

    steps:
    - uses: actions/checkout@v2

    - uses: INTI-CMNB/KiBot@92fac3958665528621f09a5d8af0b92e8d88cc32
      with:
        kicad: 5
        dir: default
        variant: default
        skip: all

    - name: upload results
      uses: actions/upload-artifact@v2
      with:
        name: default_variant
        path: default


  USB:
    name: "USB variant"
    runs-on: ubuntu-latest
    needs: [ERC, DRC]

    steps:
    - uses: actions/checkout@v2

    - uses: INTI-CMNB/KiBot@92fac3958665528621f09a5d8af0b92e8d88cc32
      with:
        kicad: 5
        dir: USB
        variant: USB
        skip: all

    - name: upload results
      uses: actions/upload-artifact@v2
      with:
        name: USB_variant
        path: USB


  XTAL:
    name: "XTAL variant"
    runs-on: ubuntu-latest
    needs: [ERC, DRC]

    steps:
    - uses: actions/checkout@v2

    - uses: INTI-CMNB/KiBot@92fac3958665528621f09a5d8af0b92e8d88cc32
      with:
        kicad: 5
        dir: XTAL
        variant: XTAL
        skip: all

    - name: upload results
      uses: actions/upload-artifact@v2
      with:
        name: XTAL_variant
        path: XTAL
