name: "Variants demo using GitHub actions"

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    paths:
      - '*.sch'
      - '*.kicad_pcb'
      - '*.kibot.yaml'
      - 'Makefile'
      - '.github/workflows/kibot_action.yml'
  pull_request:
    paths:
      - '*.sch'
      - '*.kicad_pcb'
      - '*.kibot.yaml'
      - 'Makefile'
      - '.github/workflows/kibot_action.yml'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  default:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: INTI-CMNB/KiBot@v2
      with:
        config: ardu_prog.kibot.yaml
        dir: default
        variant: default
    - name: upload results
      uses: actions/upload-artifact@v2
      with:
        name: default_variant
        path: default

  USB:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: INTI-CMNB/KiBot@v2
      with:
        config: ardu_prog.kibot.yaml
        dir: USB
        variant: USB
    - name: upload results
      uses: actions/upload-artifact@v2
      with:
        name: USB_variant
        path: USB

  XTAL:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: INTI-CMNB/KiBot@v2
      with:
        config: ardu_prog.kibot.yaml
        dir: XTAL
        variant: XTAL
    - name: upload results
      uses: actions/upload-artifact@v2
      with:
        name: XTAL_variant
        path: XTAL
