name: "Variants demo using GitHub actions"

# Controls when the action will run.
on:
  push:
    paths:
      - '*.kicad_sch'
      - '*.kicad_pcb'
      - '*.kibot.yaml'
      - 'Makefile'
      - '.github/workflows/kibot_action.yml'
  pull_request:
    paths:
      - '*.kicad_sch'
      - '*.kicad_pcb'
      - '*.kibot.yaml'
      - 'Makefile'
      - '.github/workflows/kibot_action.yml'
  repository_dispatch:
    types: [run_gha]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  ERC:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Run ERC
      uses: INTI-CMNB/KiBot@v2_k6
      with:
        dir: Generated
        skip: run_drc
        targets: __NONE__

    - name: Retrieve results
      uses: actions/upload-artifact@v3
      with:
        name: ERC_Output
        path: Generated


  DRC:
    runs-on: ubuntu-latest
    needs: ERC

    steps:
    - uses: actions/checkout@v3

    - name: Run DRC
      uses: INTI-CMNB/KiBot@v2_k6
      with:
        dir: Generated
        skip: run_erc
        targets: __NONE__

    - name: Retrieve results
      uses: actions/upload-artifact@v3
      with:
        name: DRC_Output
        path: Generated


  default:
    name: "Default variant"
    runs-on: ubuntu-latest
    needs: [ERC, DRC]

    steps:
    - uses: actions/checkout@v3

    - uses: INTI-CMNB/KiBot@v2_k6
      with:
        dir: default
        variant: default
        skip: all

    - name: upload results
      uses: actions/upload-artifact@v3
      with:
        name: default_variant
        path: default


  USB:
    name: "USB variant"
    runs-on: ubuntu-latest
    needs: [ERC, DRC]

    steps:
    - uses: actions/checkout@v3

    - uses: INTI-CMNB/KiBot@v2_k6
      with:
        dir: USB
        variant: USB
        skip: all

    - name: upload results
      uses: actions/upload-artifact@v3
      with:
        name: USB_variant
        path: USB


  XTAL:
    name: "XTAL variant"
    runs-on: ubuntu-latest
    needs: [ERC, DRC]

    steps:
    - uses: actions/checkout@v3

    - uses: INTI-CMNB/KiBot@v2_k6
      with:
        dir: XTAL
        variant: XTAL
        skip: all

    - name: upload results
      uses: actions/upload-artifact@v3
      with:
        name: XTAL_variant
        path: XTAL
